#!/bin/bash

# Navigate to the app directory
cd ~/lifemiles-app/test-data

# install deps
npm i

# Start the application
npm start

# Add all changes to git
git add .

# Commit the changes
git commit -m "Automated commit"

# Push the changes to the master branch
git push origin master
